function tests = testMicrophoneCountRegressions
%TESTMICROPHONECOUNTREGRESSIONS Guard against hard-coded array sizes.
tests = functiontests(localfunctions);
end

function testLocalizesWithFourMicrophones(testCase)
microphonesMeters = [ ...
    -0.70, -0.25; ...
     0.55, -0.40; ...
     0.80,  0.65; ...
    -0.45,  0.85];

verifyExactLocalization(testCase, microphonesMeters, 2);
end

function testLocalizesWithSixMicrophones(testCase)
microphonesMeters = [ ...
    -0.90, -0.15; ...
    -0.35, -0.75; ...
     0.40, -0.65; ...
     0.95,  0.05; ...
     0.50,  0.90; ...
    -0.65,  0.70];

verifyExactLocalization(testCase, microphonesMeters, 4);
end

function testLocalizesWithEightMicrophones(testCase)
microphonesMeters = [ ...
    -1.00, -0.20; ...
    -0.70, -0.85; ...
    -0.05, -0.95; ...
     0.75, -0.70; ...
     1.05,  0.10; ...
     0.60,  0.85; ...
    -0.15,  1.05; ...
    -0.85,  0.60];

verifyExactLocalization(testCase, microphonesMeters, 7);
end

function verifyExactLocalization(testCase, microphonesMeters, referenceIndex)
sourceMeters = [0.23, 0.37];
speedMetersPerSecond = 343;
microphoneCount = size(microphonesMeters, 1);
tdoasSeconds = micloc.predictTDOAs(sourceMeters, microphonesMeters, ...
    speedMetersPerSecond, referenceIndex);

[estimatedMeters, diagnostics] = micloc.estimateSourcePosition( ...
    tdoasSeconds, microphonesMeters, speedMetersPerSecond, ...
    referenceIndex, createSettings());

verifySize(testCase, tdoasSeconds, [microphoneCount, 1]);
verifySize(testCase, diagnostics.residualVectorSeconds, ...
    [microphoneCount - 1, 1]);
verifyTrue(testCase, diagnostics.solverSucceeded, diagnostics.solverMessage);
verifyEqual(testCase, estimatedMeters, sourceMeters, 'AbsTol', 1e-7);
verifyLessThan(testCase, diagnostics.residualNormSeconds, 1e-9);
end

function settings = createSettings
config = micloc.defaultConfig();
settings = config.localization;
settings.initialGuessMeters = [-0.2, 0.1];
settings.lowerBoundsMeters = [-2, -2];
settings.upperBoundsMeters = [2, 2];
settings.maxIterations = 500;
settings.maxFunctionEvaluations = 5000;
settings.functionTolerance = 1e-14;
settings.stepTolerance = 1e-14;
settings.optimalityTolerance = 1e-14;
end
