function maximumTDOASamples = calculateMaximumTDOASamples( ...
        microphonePositionsMeters, referenceMicrophoneIndex, ...
        sampleRateHz, speedOfSoundMetersPerSecond)
%CALCULATEMAXIMUMTDOASAMPLES Calculate geometry-derived TDOA search bounds.
%   BOUNDS = MICLOC.CALCULATEMAXIMUMTDOASAMPLES(MICROPHONES, REFERENCE,
%   SAMPLERATE, SPEED) returns one nonnegative integer sample bound per
%   microphone. Each bound is ceil(distance-to-reference * SAMPLERATE /
%   SPEED), so a physically valid fractional TDOA near the boundary remains
%   inside an integer-lag search. The reference microphone bound is zero.
%
%   MICROPHONES is an N-by-2 coordinate matrix in metres, SAMPLERATE is in
%   hertz, and SPEED is in metres per second. The result constrains a
%   direct-path TDOA; it is not a confidence interval or room model.

microphonePositionsMeters = micloc.validateMicrophonePositions( ...
    microphonePositionsMeters);
microphoneCount = size(microphonePositionsMeters, 1);
validateattributes(referenceMicrophoneIndex, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'integer', '>=', 1, ...
    '<=', microphoneCount}, mfilename, 'referenceMicrophoneIndex');
validateattributes(sampleRateHz, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'positive'}, mfilename, 'sampleRateHz');
validateattributes(speedOfSoundMetersPerSecond, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'positive'}, mfilename, ...
    'speedOfSoundMetersPerSecond');

referencePositionMeters = ...
    microphonePositionsMeters(referenceMicrophoneIndex, :);
separationsMeters = vecnorm( ...
    microphonePositionsMeters - referencePositionMeters, 2, 2);
maximumTDOASamples = ceil( ...
    separationsMeters * sampleRateHz / speedOfSoundMetersPerSecond);
maximumTDOASamples(referenceMicrophoneIndex) = 0;
end
