function [estimatedPositionMeters, diagnostics] = estimateSourcePosition( ...
        measuredTDOAsSeconds, microphonePositionsMeters, ...
        speedOfSoundMetersPerSecond, referenceMicrophoneIndex, ...
        localizationSettings)
%ESTIMATESOURCEPOSITION Estimate a 2D source from measured TDOAs.
%   POSITION = MICLOC.ESTIMATESOURCEPOSITION(TDOAS, MICROPHONES, SPEED,
%   REFERENCE, SETTINGS) minimizes all non-reference TDOA residuals using
%   bounded nonlinear least squares. TDOAS is N-by-1 in seconds and follows
%   the convention arrivalTime(i) - arrivalTime(REFERENCE). POSITION is a
%   1-by-2 coordinate in metres.
%
%   SETTINGS must contain initialGuessMeters, lowerBoundsMeters,
%   upperBoundsMeters, maxIterations, maxFunctionEvaluations,
%   functionTolerance, stepTolerance, optimalityTolerance, and
%   solverDisplay.
%
%   [POSITION, DIAGNOSTICS] preserves the solver exit flag, status message,
%   iterations, function evaluations, termination reason, residual
%   statistics, first-order optimality, bounds, and geometry ambiguity. A
%   non-convergent solver result is returned with solverSucceeded=false;
%   it is not silently converted into success.

micloc.validateMicrophonePositions(microphonePositionsMeters);
validateattributes(speedOfSoundMetersPerSecond, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'positive'}, mfilename, ...
    'speedOfSoundMetersPerSecond');
microphoneCount = size(microphonePositionsMeters, 1);
validateattributes(referenceMicrophoneIndex, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'integer', '>=', 1, '<=', microphoneCount}, ...
    mfilename, 'referenceMicrophoneIndex');
validateMeasuredTDOAs(measuredTDOAsSeconds, microphoneCount, ...
    referenceMicrophoneIndex);
validateLocalizationSettings(localizationSettings);

initialGuessMeters = localizationSettings.initialGuessMeters;
lowerBoundsMeters = localizationSettings.lowerBoundsMeters;
upperBoundsMeters = localizationSettings.upperBoundsMeters;
if any(lowerBoundsMeters > upperBoundsMeters)
    error('micloc:estimateSourcePosition:InvalidBounds', ...
        'Each lower bound must be less than or equal to its upper bound.');
end
if any(initialGuessMeters < lowerBoundsMeters ...
        | initialGuessMeters > upperBoundsMeters)
    error('micloc:estimateSourcePosition:InitialGuessOutsideBounds', ...
        'The initial source-position guess must lie within the bounds.');
end

micloc.localizationResiduals(initialGuessMeters, measuredTDOAsSeconds, ...
    microphonePositionsMeters, speedOfSoundMetersPerSecond, ...
    referenceMicrophoneIndex);

solverOptions = optimoptions('lsqnonlin', ...
    'Display', char(localizationSettings.solverDisplay), ...
    'MaxIterations', localizationSettings.maxIterations, ...
    'MaxFunctionEvaluations', ...
    localizationSettings.maxFunctionEvaluations, ...
    'FunctionTolerance', localizationSettings.functionTolerance, ...
    'StepTolerance', localizationSettings.stepTolerance, ...
    'OptimalityTolerance', localizationSettings.optimalityTolerance);
objectiveFunction = @(positionMeters) micloc.localizationResiduals( ...
    positionMeters(:).', measuredTDOAsSeconds, microphonePositionsMeters, ...
    speedOfSoundMetersPerSecond, referenceMicrophoneIndex);

[estimatedPositionMeters, residualSumOfSquares, residualVectorSeconds, ...
    exitFlag, solverOutput] = lsqnonlin(objectiveFunction, ...
    initialGuessMeters, lowerBoundsMeters, upperBoundsMeters, solverOptions);
estimatedPositionMeters = estimatedPositionMeters(:).';

[geometryRank, isLinearGeometry, halfPlaneConstraintApplied] = ...
    analyzeGeometryAndBounds(microphonePositionsMeters, ...
    lowerBoundsMeters, upperBoundsMeters);

diagnostics.exitFlag = exitFlag;
diagnostics.solverSucceeded = exitFlag > 0;
diagnostics.iterationCount = getOutputField(solverOutput, 'iterations', NaN);
diagnostics.functionEvaluationCount = getOutputField( ...
    solverOutput, 'funcCount', NaN);
diagnostics.terminationReason = classifyTermination( ...
    exitFlag, diagnostics.iterationCount, ...
    diagnostics.functionEvaluationCount, localizationSettings);
diagnostics.residualNormSeconds = norm(residualVectorSeconds);
diagnostics.maximumAbsoluteResidualSeconds = ...
    max(abs(residualVectorSeconds));
diagnostics.residualCount = numel(residualVectorSeconds);
diagnostics.residualSumOfSquaresSecondsSquared = residualSumOfSquares;
diagnostics.residualVectorSeconds = residualVectorSeconds;
diagnostics.firstOrderOptimality = getOutputField( ...
    solverOutput, 'firstorderopt', NaN);
diagnostics.solverMessage = getOutputField(solverOutput, 'message', '');
diagnostics.algorithm = getOutputField(solverOutput, 'algorithm', '');
diagnostics.initialGuessMeters = initialGuessMeters;
diagnostics.lowerBoundsMeters = lowerBoundsMeters;
diagnostics.upperBoundsMeters = upperBoundsMeters;
diagnostics.geometryRank = geometryRank;
diagnostics.isLinearGeometry = isLinearGeometry;
diagnostics.halfPlaneConstraintApplied = halfPlaneConstraintApplied;
diagnostics.mirrorAmbiguityRemains = ...
    isLinearGeometry && ~halfPlaneConstraintApplied;
diagnostics.rawSolverOutput = solverOutput;
end

function validateMeasuredTDOAs(tdoasSeconds, microphoneCount, referenceIndex)
isValidVector = isnumeric(tdoasSeconds) && isreal(tdoasSeconds) ...
    && isvector(tdoasSeconds) && numel(tdoasSeconds) == microphoneCount ...
    && all(isfinite(tdoasSeconds));
if ~isValidVector
    error('micloc:estimateSourcePosition:InvalidMeasuredTDOAs', ...
        ['Measured TDOAs must be a finite real vector with one value ' ...
        'per microphone.']);
end

if tdoasSeconds(referenceIndex) ~= 0
    error('micloc:estimateSourcePosition:NonzeroReferenceTDOA', ...
        'The measured TDOA at the reference microphone must be zero.');
end
end

function validateLocalizationSettings(settings)
if ~(isstruct(settings) && isscalar(settings))
    error('micloc:estimateSourcePosition:InvalidSettings', ...
        'Localization settings must be a scalar structure.');
end
requiredFields = { ...
    'initialGuessMeters', 'lowerBoundsMeters', 'upperBoundsMeters', ...
    'maxIterations', 'maxFunctionEvaluations', 'functionTolerance', ...
    'stepTolerance', 'optimalityTolerance', 'solverDisplay'};
missingFields = requiredFields(~isfield(settings, requiredFields));
if ~isempty(missingFields)
    error('micloc:estimateSourcePosition:MissingSetting', ...
        'Required localization setting %s is missing.', missingFields{1});
end

validateattributes(settings.initialGuessMeters, {'numeric'}, ...
    {'real', 'finite', 'size', [1, 2]}, mfilename, ...
    'localizationSettings.initialGuessMeters');
validateBoundVector(settings.lowerBoundsMeters, ...
    'localizationSettings.lowerBoundsMeters');
validateBoundVector(settings.upperBoundsMeters, ...
    'localizationSettings.upperBoundsMeters');
validateattributes(settings.maxIterations, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'integer', 'positive'}, mfilename, ...
    'localizationSettings.maxIterations');
validateattributes(settings.maxFunctionEvaluations, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'integer', 'positive'}, mfilename, ...
    'localizationSettings.maxFunctionEvaluations');
validatePositiveScalar(settings.functionTolerance, ...
    'localizationSettings.functionTolerance');
validatePositiveScalar(settings.stepTolerance, ...
    'localizationSettings.stepTolerance');
validatePositiveScalar(settings.optimalityTolerance, ...
    'localizationSettings.optimalityTolerance');

displayValue = settings.solverDisplay;
isCharacterRow = ischar(displayValue) && isrow(displayValue) ...
    && ~isempty(displayValue);
isStringScalar = isstring(displayValue) && isscalar(displayValue) ...
    && strlength(displayValue) > 0;
if ~(isCharacterRow || isStringScalar) ...
        || ~any(strcmpi(char(displayValue), {'off', 'iter', 'final'}))
    error('micloc:estimateSourcePosition:InvalidSolverDisplay', ...
        'Solver display must be ''off'', ''iter'', or ''final''.');
end
end

function validateBoundVector(value, argumentName)
if ~(isnumeric(value) && isreal(value) && isequal(size(value), [1, 2]) ...
        && ~any(isnan(value)))
    error('micloc:estimateSourcePosition:InvalidBounds', ...
        '%s must be a real 1-by-2 vector without NaN values.', argumentName);
end
end

function validatePositiveScalar(value, argumentName)
if ~(isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value > 0)
    error('micloc:estimateSourcePosition:InvalidTolerance', ...
        '%s must be a positive finite scalar.', argumentName);
end
end

function [geometryRank, isLinearGeometry, halfPlaneConstraintApplied] = ...
        analyzeGeometryAndBounds(microphonePositionsMeters, ...
        lowerBoundsMeters, upperBoundsMeters)
centeredPositions = microphonePositionsMeters ...
    - mean(microphonePositionsMeters, 1);
geometryRank = rank(centeredPositions);
isLinearGeometry = geometryRank < 2;
halfPlaneConstraintApplied = false;

if isLinearGeometry && all(isfinite([lowerBoundsMeters, upperBoundsMeters]))
    [~, ~, rightSingularVectors] = svd(centeredPositions, 0);
    arrayDirection = rightSingularVectors(:, 1);
    arrayNormal = [-arrayDirection(2); arrayDirection(1)];
    boundCorners = [ ...
        lowerBoundsMeters; ...
        lowerBoundsMeters(1), upperBoundsMeters(2); ...
        upperBoundsMeters(1), lowerBoundsMeters(2); ...
        upperBoundsMeters];
    arrayCentroid = mean(microphonePositionsMeters, 1);
    signedCornerDistances = (boundCorners - arrayCentroid) * arrayNormal;
    geometryTolerance = 100 * eps(max(1, max(abs(boundCorners), [], 'all')));
    halfPlaneConstraintApplied = ...
        all(signedCornerDistances >= -geometryTolerance) ...
        || all(signedCornerDistances <= geometryTolerance);
end
end

function value = getOutputField(structure, fieldName, defaultValue)
if isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end

function reason = classifyTermination(exitFlag, iterationCount, ...
        functionEvaluationCount, settings)
if exitFlag > 0
    reason = "converged";
elseif exitFlag == 0 ...
        && functionEvaluationCount >= settings.maxFunctionEvaluations
    reason = "function-evaluation-limit";
elseif exitFlag == 0 && iterationCount >= settings.maxIterations
    reason = "iteration-limit";
elseif exitFlag == 0
    reason = "solver-limit";
elseif exitFlag == -1
    reason = "stopped-by-output-function";
elseif exitFlag == -2
    reason = "no-feasible-point";
else
    reason = "solver-failure";
end
end
