function config = validateConfig(config)
%VALIDATECONFIG Validate a microphone-localization configuration.
%   CONFIG = MICLOC.VALIDATECONFIG(CONFIG) validates the complete public
%   simulation configuration and returns it unchanged. Coordinate values
%   are in metres, time values are in seconds, sampling frequency is in
%   hertz, SNR is in decibels, and sound speed is in metres per second.

if ~(isstruct(config) && isscalar(config))
    error('micloc:validateConfig:InvalidConfiguration', ...
        'Configuration must be a scalar structure.');
end

requireFields(config, { ...
    'sampleRateHz', 'durationSeconds', 'randomSeed', ...
    'speedOfSoundMetersPerSecond', 'microphonePositionsMeters', ...
    'sourcePositionMeters', 'referenceMicrophoneIndex', 'delayMethod', ...
    'noise', 'lms', 'localization', 'plot'}, 'config');

validateattributes(config.sampleRateHz, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'positive'}, mfilename, ...
    'config.sampleRateHz');
validateattributes(config.durationSeconds, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'positive'}, mfilename, ...
    'config.durationSeconds');
validateattributes(config.speedOfSoundMetersPerSecond, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'positive'}, mfilename, ...
    'config.speedOfSoundMetersPerSecond');
validateattributes(config.randomSeed, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'integer', 'nonnegative', ...
    '<=', double(intmax('uint32'))}, mfilename, 'config.randomSeed');

micloc.validateMicrophonePositions(config.microphonePositionsMeters);
microphoneCount = size(config.microphonePositionsMeters, 1);

validateattributes(config.sourcePositionMeters, {'numeric'}, ...
    {'real', 'finite', 'size', [1, 2]}, mfilename, ...
    'config.sourcePositionMeters');
validateattributes(config.referenceMicrophoneIndex, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'integer', '>=', 1, '<=', microphoneCount}, ...
    mfilename, 'config.referenceMicrophoneIndex');
validateTextChoice(config.delayMethod, {'integer', 'fractional'}, ...
    'config.delayMethod');

validateNestedStructure(config.noise, {'enabled', 'snrDb'}, 'config.noise');
validateLogicalScalar(config.noise.enabled, 'config.noise.enabled');
if ~(isnumeric(config.noise.snrDb) && isreal(config.noise.snrDb) ...
        && isscalar(config.noise.snrDb) && ~isnan(config.noise.snrDb) ...
        && (isfinite(config.noise.snrDb) || config.noise.snrDb == Inf))
    invalidField('config.noise.snrDb', ...
        'SNR must be a finite real scalar or positive infinity.');
end

validateNestedStructure(config.lms, { ...
    'filterLength', 'stepSize', 'bulkDelaySamples', ...
    'storeCoefficientHistory'}, 'config.lms');
validateattributes(config.lms.filterLength, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'integer', 'positive'}, mfilename, ...
    'config.lms.filterLength');
validateattributes(config.lms.stepSize, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'positive'}, mfilename, ...
    'config.lms.stepSize');
validateattributes(config.lms.bulkDelaySamples, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'integer', 'nonnegative'}, mfilename, ...
    'config.lms.bulkDelaySamples');
validateLogicalScalar(config.lms.storeCoefficientHistory, ...
    'config.lms.storeCoefficientHistory');

validateNestedStructure(config.localization, { ...
    'initialGuessMeters', 'lowerBoundsMeters', 'upperBoundsMeters', ...
    'maxIterations', 'maxFunctionEvaluations', 'functionTolerance', ...
    'stepTolerance', 'optimalityTolerance', 'solverDisplay'}, ...
    'config.localization');
validateattributes(config.localization.initialGuessMeters, {'numeric'}, ...
    {'real', 'finite', 'size', [1, 2]}, mfilename, ...
    'config.localization.initialGuessMeters');
validateBoundVector(config.localization.lowerBoundsMeters, ...
    'config.localization.lowerBoundsMeters');
validateBoundVector(config.localization.upperBoundsMeters, ...
    'config.localization.upperBoundsMeters');

lowerBounds = config.localization.lowerBoundsMeters;
upperBounds = config.localization.upperBoundsMeters;
initialGuess = config.localization.initialGuessMeters;
if any(lowerBounds > upperBounds)
    invalidField('config.localization', ...
        'Each lower bound must be less than or equal to its upper bound.');
end
if any(initialGuess < lowerBounds | initialGuess > upperBounds)
    invalidField('config.localization.initialGuessMeters', ...
        'The initial guess must lie within the localization bounds.');
end

validateattributes(config.localization.maxIterations, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'integer', 'positive'}, mfilename, ...
    'config.localization.maxIterations');
validateattributes(config.localization.maxFunctionEvaluations, {'numeric'}, ...
    {'real', 'scalar', 'finite', 'integer', 'positive'}, mfilename, ...
    'config.localization.maxFunctionEvaluations');
validatePositiveTolerance(config.localization.functionTolerance, ...
    'config.localization.functionTolerance');
validatePositiveTolerance(config.localization.stepTolerance, ...
    'config.localization.stepTolerance');
validatePositiveTolerance(config.localization.optimalityTolerance, ...
    'config.localization.optimalityTolerance');
validateTextChoice(config.localization.solverDisplay, ...
    {'off', 'iter', 'final'}, 'config.localization.solverDisplay');

validateNestedStructure(config.plot, {'enabled'}, 'config.plot');
validateLogicalScalar(config.plot.enabled, 'config.plot.enabled');
end

function requireFields(structure, requiredFields, structureName)
missingFields = requiredFields(~isfield(structure, requiredFields));
if ~isempty(missingFields)
    error('micloc:validateConfig:MissingField', ...
        'Required field %s.%s is missing.', structureName, missingFields{1});
end
end

function validateNestedStructure(value, requiredFields, fieldName)
if ~(isstruct(value) && isscalar(value))
    invalidField(fieldName, 'Value must be a scalar structure.');
end
requireFields(value, requiredFields, fieldName);
end

function validateLogicalScalar(value, fieldName)
if ~(islogical(value) && isscalar(value))
    invalidField(fieldName, 'Value must be a logical scalar.');
end
end

function validateBoundVector(value, fieldName)
if ~(isnumeric(value) && isreal(value) && isequal(size(value), [1, 2]) ...
        && ~any(isnan(value)))
    invalidField(fieldName, ...
        'Bounds must be a real 1-by-2 vector without NaN values.');
end
end

function validatePositiveTolerance(value, fieldName)
if ~(isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value > 0)
    invalidField(fieldName, 'Tolerance must be a positive finite scalar.');
end
end

function validateTextChoice(value, choices, fieldName)
isCharacterRow = ischar(value) && isrow(value) && ~isempty(value);
isStringScalar = isstring(value) && isscalar(value) && strlength(value) > 0;
if ~(isCharacterRow || isStringScalar)
    invalidField(fieldName, 'Value must be a nonempty text scalar.');
end
if ~any(strcmpi(char(value), choices))
    invalidField(fieldName, sprintf( ...
        'Unsupported value. Expected one of: %s.', strjoin(choices, ', ')));
end
end

function invalidField(fieldName, message)
error('micloc:validateConfig:InvalidField', '%s: %s', fieldName, message);
end
